import React from "react";
import { useNavigate } from "react-router-dom";
import { Helmet } from "react-helmet-async";
import { FileText, ArrowLeft, Shield } from "lucide-react";
import { motion } from "framer-motion";

const Terms = () => {
  const navigate = useNavigate();

  const sections = [
    {
      num: "1",
      title: "Introduction",
      content: "Welcome to Maatriva. By purchasing or using our website, mobile application, and the world's first AI-powered smart baby cradle, you agree to comply with and be bound by these Terms and Conditions."
    },
    {
      num: "2",
      title: "Product Overview & App Usage",
      content: "Maatriva provides a smart cradle designed to learn your baby's needs and automate soothing routines. Our services require users to set up the device, connect it to the mobile app, and customize preferences such as rocking speed, music, and temperature. By using our product, you gain access to features like smart soothing, climate control monitoring, and a sound library containing over 100 curated lullabies and white noise options."
    },
    {
      num: "3",
      title: "Health Monitoring & Medical Disclaimer",
      content: "Our product includes advanced AI health monitoring and disease detection capabilities for conditions including Cystic Fibrosis, Sleep Apnea, Tetralogy of Fallot, Epilepsy, Hydrocephalus, and Arrhythmias.",
      alert: "Disclaimer: While Maatriva features medical-grade materials and built-in safety sensors, the cradle and its monitoring systems are intended to provide peace of mind and data insights. They do not replace professional medical advice, diagnosis, or treatment from a qualified healthcare provider."
    },
    {
      num: "4",
      title: "Pricing, Plans, and Subscriptions",
      content: "We offer several purchasing options to suit your needs:",
      bullets: [
        "Hardware: Customers may select from our Basic, Standard, or Pro cradle models.",
        "AI Subscription: Our advanced AI health monitoring and assistant system is available for ₹10,000. This subscription includes deep analysis, disease detection, meaning of diseases, caretaker access, and AI chat/voice assistants.",
        "Enterprise: Custom plans are available for hospitals and daycare centres, which include bulk deployment, a central monitoring dashboard, custom integrations, and dedicated support."
      ]
    },
    {
      num: "5",
      title: "AI Learning and Data",
      content: "The Maatriva cradle utilizes an intelligent system to adapt to your baby's unique sleep patterns and preferences over time. The handling of user and health data generated by the AI system is governed by our separate Privacy Terms."
    },
    {
      num: "6",
      title: "Safety and Liability",
      content: "Setup can be completed in under 5 minutes. While our product is designed with your baby's comfort and safety in mind, the user assumes all responsibility for ensuring the cradle is assembled and used according to the provided instructions. The intelligent system will automatically respond to your baby's needs, but it is not a substitute for parental supervision."
    },
    {
      num: "7",
      title: "Contact and Support",
      content: "If you require assistance with your product, app connectivity, or subscription, our support team is available to help anytime via the \"Contact Us\" section on our website."
    }
  ];

  return (
    <div className="min-h-screen bg-[var(--bg-secondary)] text-[var(--text)] fade-in pb-20 pt-28">
      <Helmet>
        <title>Terms & Conditions | Maatriva</title>
        <meta name="description" content="Read the Terms and Conditions for purchasing and using Maatriva smart cradle and applications." />
      </Helmet>

      {/* Floating Background Glows */}
      <div className="absolute top-0 left-0 w-96 h-96 bg-[var(--primary)]/10 rounded-full blur-3xl pointer-events-none" />
      <div className="absolute bottom-20 right-0 w-96 h-96 bg-[var(--primary-light)]/10 rounded-full blur-3xl pointer-events-none" />

      <div className="max-w-4xl mx-auto px-6 relative z-10">
        {/* Back Button */}
        <button
          onClick={() => navigate(-1)}
          className="flex items-center gap-2 px-5 py-2.5 clay-badge hover:scale-105 transition-transform mb-8 font-bold text-sm cursor-pointer"
        >
          <ArrowLeft size={16} />
          Go Back
        </button>

        {/* Page Header */}
        <div className="text-center mb-12">
          <div className="inline-flex items-center justify-center p-3 rounded-2xl clay-badge mb-4 text-[var(--primary)]">
            <FileText size={32} />
          </div>
          <h1 className="text-4xl md:text-5xl font-black text-[var(--text-dark)] leading-tight">
            Terms & Conditions
          </h1>
          <p className="text-[var(--text-light)] font-medium mt-3">
            Last updated: June 2026 • Maatriva Smart Baby Cradle
          </p>
        </div>

        {/* Terms Content Container */}
        <div className="clay-card p-8 md:p-12 space-y-10">
          {sections.map((sec) => (
            <motion.div
              key={sec.num}
              initial={{ opacity: 0, y: 15 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.5 }}
              className="space-y-4"
            >
              <div className="flex items-center gap-3">
                <span className="flex items-center justify-center w-8 h-8 rounded-full clay-badge text-[var(--primary)] font-bold text-sm">
                  {sec.num}
                </span>
                <h2 className="text-xl font-bold text-[var(--text-dark)]">
                  {sec.title}
                </h2>
              </div>
              
              <p className="text-base leading-relaxed text-[var(--text)] font-medium pl-11">
                {sec.content}
              </p>

              {sec.bullets && (
                <ul className="list-disc pl-16 space-y-3">
                  {sec.bullets.map((b, i) => (
                    <li key={i} className="text-sm leading-relaxed text-[var(--text-light)] font-medium">
                      {b}
                    </li>
                  ))}
                </ul>
              )}

              {sec.alert && (
                <div className="ml-11 p-4 bg-orange-50 border border-orange-100 rounded-2xl flex gap-3 items-start text-orange-800 text-sm leading-relaxed font-semibold">
                  <Shield className="w-5 h-5 shrink-0 text-orange-600 mt-0.5" />
                  <p>{sec.alert}</p>
                </div>
              )}
            </motion.div>
          ))}
        </div>

        {/* Footer info */}
        <div className="text-center mt-12 text-sm text-[var(--text-light)] font-bold">
          Copyright © 2026 Maatriva
        </div>
      </div>
    </div>
  );
};

export default Terms;
