export const termsSections = [
  {
    num: "1",
    title: "Introduction",
    content: "Welcome to Maatriva. By purchasing or using our website, mobile application, and the world's first AI-powered smart baby cradle, you agree to comply with and be bound by these Terms and Conditions."
  },
  {
    num: "2",
    title: "Product Overview & App Usage",
    content: "Maatriva provides a smart cradle designed to learn your baby's needs and automate soothing routines. Our services require users to set up the device, connect it to the mobile app, and customize preferences such as rocking speed, music, and temperature. By using our product, you gain access to features like smart soothing, climate control monitoring, and a sound library containing over 100 curated lullabies and white noise options."
  },
  {
    num: "3",
    title: "Health Monitoring & Medical Disclaimer",
    content: "Our product includes advanced AI health monitoring and disease detection capabilities for conditions including Cystic Fibrosis, Sleep Apnea, Tetralogy of Fallot, Epilepsy, Hydrocephalus, and Arrhythmias.",
    alert: "Disclaimer: While Maatriva features medical-grade materials and built-in safety sensors, the cradle and its monitoring systems are intended to provide peace of mind and data insights. They do not replace professional medical advice, diagnosis, or treatment from a qualified healthcare provider."
  },
  {
    num: "4",
    title: "Pricing, Plans, and Subscriptions",
    content: "We offer several purchasing options to suit your needs:",
    bullets: [
      "Hardware: Customers may select from our Basic, Standard, or Pro cradle models.",
      "AI Subscription: Our advanced AI health monitoring and assistant system is available for ₹10,000. This subscription includes deep analysis, disease detection, meaning of diseases, caretaker access, and AI chat/voice assistants.",
      "Enterprise: Custom plans are available for hospitals and daycare centres, which include bulk deployment, a central monitoring dashboard, custom integrations, and dedicated support."
    ]
  },
  {
    num: "5",
    title: "AI Learning and Data",
    content: "The Maatriva cradle utilizes an intelligent system to adapt to your baby's unique sleep patterns and preferences over time. The handling of user and health data generated by the AI system is governed by our separate Privacy Terms."
  },
  {
    num: "6",
    title: "Safety and Liability",
    content: "Setup can be completed in under 5 minutes. While our product is designed with your baby's comfort and safety in mind, the user assumes all responsibility for ensuring the cradle is assembled and used according to the provided instructions. The intelligent system will automatically respond to your baby's needs, but it is not a substitute for parental supervision."
  },
  {
    num: "7",
    title: "Contact and Support",
    content: "If you require assistance with your product, app connectivity, or subscription, our support team is available to help anytime via the \"Contact Us\" section on our website."
  }
];
